[package]
name = "graph-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
neo4rs = "0.8.0"
tokio = "1.47.1"
uuid = "1.18.1"
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
